set nocompatible               " be iMproved
filetype off                   " required!
syntax on
set rtp+=~/.vim/bundle/Vundle.vim

set hlsearch 
set incsearch
set laststatus=2
let g:airline_theme = 'wombat'
let g:airline#extensions#tabline#enabled = 1
let g:loaded_dispatch = 0
let g:syntastic_cpp_compiler = 'clang++'
let g:syntastic_cpp_compiler_options = ' -std=c++11 -stdlib=libc++'
let g:cmake_build_type = 'Debug'
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let mapleader = ","
set smartindent
set autoindent
set tabstop=4
set shiftwidth=4
set expandtab
" no spell by default
set nospell
set spelllang=en_us,pl
set nu
set modeline
set modelines=5

" Auto detect cores
function! SetMakeprg()
    if !empty($NUMBER_OF_PROCESSORS)
        let n = $NUMBER_OF_PROCESSORS + 0
    else
        let n = system('nproc') + 0
    endif
    let &makeprg = 'make' . (n > 1 ? (' -j'.(n + 1)) : '')
endfunction
call SetMakeprg()

au BufRead,BufNewFile *mutt* set filetype=mail
au BufRead,BufNewFile *muttrc* set filetype=muttrc
au BufRead,BufNewFile *vimpager* set nospell
autocmd BufRead,BufNewFile *.qml setfiletype qml
autocmd BufRead,BufNewFile *.go setfiletype go
autocmd FileType mail set spell
set spellfile=~/dotfiles/vim/en.utf-8.add

let g:ycm_global_ycm_extra_conf = '~/dotfiles/ycm_extra_conf.py'
syntax enable
" Use the right side of the screen
let g:buffergator_viewport_split_policy = 'R'

call vundle#begin()

" My Plugins here:
"
Plugin 'gmarik/Vundle.vim'
Plugin 'kien/ctrlp.vim'
Plugin 'wincent/command-t'
Plugin 'bling/vim-airline'
Plugin 'Valloric/YouCompleteMe'
Plugin 'bling/vim-bufferline'
Plugin 'Yggdroot/indentLine'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdtree'
Plugin 'mhinz/vim-startify'
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'garbas/vim-snipmate'
Plugin 'honza/vim-snippets'
Plugin 'drmikehenry/vim-headerguard'
Plugin 'vim-scripts/a.vim'
Plugin 'vhdirk/vim-cmake'
Plugin 'jlanzarotta/bufexplorer'
Plugin 'vim-scripts/lbdbq'
Plugin 'morhetz/gruvbox'
Plugin 'farseer90718/vim-taskwarrior'
Plugin '29decibel/codeschool-vim-theme'
Plugin 'fatih/vim-go'
Plugin 'peterhoeg/vim-qml'
Plugin 'jeetsukumaran/vim-buffergator'
Plugin 'SirVer/ultisnips'
Plugin 'majutsushi/tagbar'
Plugin 'wincent/Command-T'
Plugin 'octol/vim-cpp-enhanced-highlight'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'rking/ag.vim'


call vundle#end() 
filetype plugin indent on     " required! 
"
" Brief help
" :PluginList          - list configured bundles
" :PluginInstall(!)    - install(update) bundles
" :PluginSearch(!) foo - search(or refresh cache first) for foo
" :PluginClean(!)      - confirm(or auto-approve) removal of unused bundles
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Plugin command are not allowed..
set background=dark
colorscheme burnttoast256

" underline spelling mistakes
hi clear SpellBad
hi SpellBad cterm=underline

" Mapping
nnoremap <leader>g :YcmCompleter GoToDefinitionElseDeclaration<CR>
