#!/bin/sh
. "${HOME}/.cache/wal/colors.sh"

bspc config border_width        4
bspc config window_gap          2
i=1
for monitor in $(bspc query -M); do
    bspc monitor $monitor \
            -d $i/{term,web,mail,dev,im,vi,vii,viii,ix,x}
        let i++
done
NMON=$i
unset i

bspc config top_padding 18 

# Visual options
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config single_monocle      true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_border_color "$color1"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

# Rules
bspc rule -a scratchpad sticky=on state=floating 

bspc rule -a Pavucontrol state=floating 
bspc rule -a QtQmlViewer state=floating 
bspc rule -a qmltestrunner state=floating
bspc rule -a feh state=floating
bspc rule -a URxvtQuake sticky=on state=floating
bspc config external_rules_command "$HOME/.config/bspwm/external_rules.sh"

~/.config/bspwm/panel/panel > /tmp/panel-log 2>&1 &
sleep 2
setxkbmap pl &
