#! /bin/sh

cd $(dirname $0)
source $(dirname $0)/config

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &
bspc config top_padding 15
conky -c ./panel_conky > "$PANEL_FIFO" &
echo "T" >  "$PANEL_FIFO" &
if [ "$1" == "e" ];then
    PANEL_GEOMETRY="1920x14+1080+0"
fi

cat "$PANEL_FIFO" \
	| ./panel_bar \
	| bar \
		-f "$FONT1"\
        -f "$FONT2"\
		-F "$COLOR_FOREGROUND"\
		-B "$COLOR_BACKGROUND"\
		-g "$PANEL_GEOMETRY"\
		-u $LINEHEIGHT &
wait
