#!/bin/bash
source $(dirname $0)/config

interface=`nmcli c | grep en | grep -v vpn | awk '{print $4}'`

icon=""
id=`nmcli c | grep $interface | grep -v vpn | awk '{print $1}'`
vpn=`nmcli c | grep vpn | grep $interface | awk '{print $1}'`


if [ "$vpn" == "" ]; then
echo "%{F$COLOR_ICON}$id%{F-}"
else 
echo "%{F$COLOR_ICON}$id[$vpn]%{F-}"
fi
