#!/bin/bash
source $(dirname $0)/config

# WIFI ICONS
# 
interface=`nmcli c | grep wl | awk '{print $4}'`

if [ "$interface" == "" ]; then
    echo ""
    exit
fi

QUAL=`iwconfig $interface | grep 'Link Quality=' | awk '{gsub(/[=/]/," "); print $3}'`
MAX=`iwconfig $interface | grep 'Link Quality=' | awk '{gsub(/[=/]/," "); print $4}'`
PERC=`echo $QUAL*100/$MAX | bc`

icon=""
essid=`nmcli c | grep $interface | awk '{print $1}'`
vpn=`nmcli c | grep vpn | grep $interface | awk '{print $1}'`
case $PERC in
	[0-4])
		icon=""
	;;
	[4-9])
		icon=""
	;;
	[2-3]*)
		icon=""
	;;
	[4-5]*)
		icon=""
	;;
	[6-7]*)
		icon=""
	;;
	*)
		icon=""
	;;
esac

if [ "$vpn" == "" ]; then
    echo "%{F$COLOR_ICON}$icon $essid%{F-}"
else 
    echo "%{F$COLOR_ICON}$icon $essid[$vpn]%{F-}"
fi
