#!/bin/bash

fetchMailOut=$(fetchmail -c -u bartosz.taczala@mobica.com -p imap --ssl imap.gmail.com)
if [ $? -ne 0 ]; then
    numberOfMails=$(cat /tmp/mails)
else
    #numberOfMails=$(fetchmail -c -u bartosz.taczala@mobica.com -p imap --ssl imap.gmail.com | awk '{print $1}')
    numberOfMails=`echo $fetchMailOut | awk '{print $1}'`
    echo $numberOfMails > /tmp/mails
fi
echo $numberOfMails

