#!/bin/sh

bspc config border_width        3
bspc config window_gap          4

i=1
for monitor in $(bspc query -M); do
bspc monitor $monitor \
        -d $i/{term,web,mail,dev,im,vi,vii,viii,ix,x}
    let i++
done
NMON=$i
unset i

bspc config top_padding 14 

# Visual options
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#332d29"
bspc config active_border_color "#817267"
bspc config focused_border_color "#504339"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true


# Rules
bspc rule -a Skype desktop=^5
bspc rule -a Pidgin desktop=^5
bspc rule -a gimp-2.8 floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a Firefox desktop=^2
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a astime sticky=on
bspc rule -a feh floating=on manage=off
bspc rule -a scratchpad sticky=on floating=on
bspc rule -a mutt desktop=^3

bspc rule -a hmi floating=on 
bspc rule -a QtQmlViewer floating=on

/home/bata/.config/bspwm/panel/panel &
sleep 2
stalonetray --dockapp-mode simple &
setxkbmap pl &

