# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh
zplug "plugins/git",   from:oh-my-zsh
zplug "lib/clipboard", from:oh-my-zsh, if:"[[ $OSTYPE == *darwin* ]]"
zplug "agkozak/zsh-z"
zplug "zsh-users/zsh-completions"

zplug romkatv/powerlevel10k, as:theme, depth:1
zplug load
unalias grm

export EDITOR=nvim
export BROWSER=firefox
export PATH=$HOME/dotfiles/bin:/usr/local/bin:$PATH

if [ -d $HOME/dev/git-fuzzy/bin ]; then
    export PATH=$HOME/dev/git-fuzzy/bin:$PATH
fi

source $HOME/dotfiles/zsh/aliases.zsh
source $HOME/dotfiles/zsh/my_fzf.sh
[ -f /usr/share/fzf/key-bindings.zsh ] && source /usr/share/fzf/key-bindings.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/dotfiles/zsh/forgit.plugin.zsh ] && source ~/dotfiles/zsh/forgit.plugin.zsh
[[ ! -f $HOME/dotfiles/zsh/p10k.zsh ]] || source $HOME/dotfiles/zsh/p10k.zsh

autoload -U edit-command-line
zle -N edit-command-line
bindkey '^xe' edit-command-line
bindkey '^x^e' edit-command-line

fpath=($fpath $HOME/dotfiles/zsh/completion)
autoload -Uz compinit && compinit
