# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
#zmodload zsh/zprof
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh
export ZPLUG_USE_CACHE=true
export ZPLUG_CACHE_DIR=$HOME/.cache/zplug
zplug "plugins/git",   from:oh-my-zsh
zplug "lib/clipboard", from:oh-my-zsh, if:"[[ $OSTYPE == *darwin* ]]"
zplug "agkozak/zsh-z"
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-history-substring-search"
zplug "ytakahashi/igit"
zplug 'unixorn/fzf-zsh-plugin'

zplug romkatv/powerlevel10k, as:theme, depth:1
zplug load
#unalias grm
alias ll='ls -lah'

export EDITOR=nvim
export BROWSER=firefox
export PATH=$HOME/dotfiles/bin:/usr/local/bin:$PATH
export HISTSIZE=100000
export SAVEHIST=100000
# don't save duplicates
setopt hist_ignore_all_dups
# don't save with space in front
setopt hist_ignore_space
setopt appendhistory
setopt inc_append_history

if [ -d $HOME/dev/git-fuzzy/bin ]; then
    export PATH=$HOME/dev/git-fuzzy/bin:$PATH
fi

source $HOME/dotfiles/zsh/aliases.zsh
source $HOME/dotfiles/zsh/my_fzf.sh
[ -f ~/dotfiles/zsh/forgit.plugin.zsh ] && source ~/dotfiles/zsh/forgit.plugin.zsh
[[ ! -f $HOME/dotfiles/zsh/p10k.zsh ]] || source $HOME/dotfiles/zsh/p10k.zsh

autoload -U edit-command-line
zle -N edit-command-line
bindkey '^xe' edit-command-line
bindkey '^x^e' edit-command-line

fpath=($fpath $HOME/dotfiles/zsh/completion)
autoload -Uz compinit && compinit

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

$HOME/dotfiles/bin/mac_change_dark_mode.sh
