source /etc/zsh/zpreztorc
source /usr/lib/prezto/init.zsh
source /usr/lib/prezto/runcoms/zshrc


export EDITOR=vim
eval `dircolors ~/.dircolors`
export TASKRC=~/ownCloud/task/work/taskrc
export TASKDATA=~/ownCloud/task/work/task
export PATH=/home/bata/.gem/ruby/2.1.0/bin:$PATH
export PATH=/home/bata/dotfiles/scripts:$PATH

export TERM=xterm-termite

if [[ $TERM == xterm-termite ]]; then
  . /etc/profile.d/vte.sh
    __vte_osc7
fi
export PAGER=/usr/bin/vimpager
alias less=$PAGER
alias zless=$PAGER

unset GREP_COLOR
unset GREP_OPTIONS

alias gst='git status'
alias gup='git pull --rebase'
alias builds='cd ~/.builds'
