# set ft=ruby
# development
brew "llvm"
brew "cmake"
brew "neovim"
brew "cppman"
brew "shfmt"
brew "ripgrep"
brew "fd"
brew "bat"
brew "lua-language-server"
brew "eza"
brew "zls"
brew "dark-notify"
cask "kitty"

# dev fonts
cask "font-iosevka"
cask "font-fira-code"

# utils
cask "whatsapp"
cask "wezterm"
cask "kitty"
cask "temurin"
